title = "Utilities"
format = "roblox"

[[classOrder]]
section = "SignaLuau"
classes = ["SignaLuau", "Signal", "SignalConnection"]

[[classOrder]]
section = "InterLink"
classes = ["InterLink", "Root", "Component"]

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "Versatile and secure Roblox utility modules"