title = "Utilities"
format = "roblox"

[[classOrder]]
section = "SignaLuau"
classes = ["Signal", "SignalConnection"]

[[classOrder]]
section = "Exceptions"
classes = ["Exceptions"]

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "Versatile and secure Roblox utility modules"