[package]
name = "gordxn-rbx/signaluau"
description = "Lightweight Luau signals and connections library. It was designed to closely mimic the behavior of the platform-native signals and connections. Please refer to the documentation site for more information and getting started."
homepage = "https://gordxn-rbx.github.io/utilities/api/Signal/"
repository = "https://github.com/gordxn-rbx/utilities"

version = "1.1.0"

license = "MIT"
authors = ["Ashton Ivy <ashtonivy23@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["node_modules"]